name: Tests

on:
  push:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+'
  pull_request:
    branches:
      - master
      - develop
      - 'v[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    # NOTE: Don't use nix in platform checks everything should be based on the host system
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-13, macos-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test ${{matrix.os}}
        run: cargo test --workspace --all-features --no-fail-fast
  wasm-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - name: Test main lib in headless Chrome
        run: nix develop .#wasm -c wasm-pack test --headless --chrome rust
      - name: Test derive lib in headless Chrome
        run: nix develop .#wasm -c wasm-pack test --headless --chrome rust/derive
